routes:
  /secret-homepage-preview/:
    controller: channel
    template: homepage

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /{slug}/
  author: /contributor/{slug}/